---
- name: Standardize Laptop Setup
  hosts: my_laptop

  vars_files:
    - vars/main.yml

  roles:
    - role: core
      tags: [core]

    - role: system
      tags: [system]

    - role: terminal
      tags: [terminal, dotfiles, fonts, starship]

    - role: languages
      tags: [languages]

    - role: docker
      tags: [docker]

