---
# ==============================================================================
# Playbook: Hadev's Workstation Setup
# Description: Main entry point. Orchestrates task imports.
# ==============================================================================

- name: Standardize Laptop Setup
  hosts: my_laptop

  # Load variables
  vars_files:
    - vars/main.yml

  # Import Task Lists
  tasks:
    - import_tasks: tasks/system.yml
    - import_tasks: tasks/filesystem.yml
    - import_tasks: tasks/pyenv.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/security.yml