---
- name: Standardize Laptop Setup
  hosts: my_laptop

  vars_files:
    - vars/main.yml

  tasks:
    - import_tasks: tasks/system.yml
      tags: [system]

    - import_tasks: tasks/security.yml
      tags: [security]

    - import_tasks: tasks/filesystem.yml
      tags: [filesystem]

    - import_tasks: tasks/docker.yml
      tags: [docker]

    - import_tasks: tasks/pyenv.yml
      tags: [pyenv]

    - import_tasks: tasks/nvm.yml
      tags: [nvm]

    - import_tasks: tasks/scripts.yml
      tags: [scripts]

    - import_tasks: tasks/dotfiles.yml
      tags: [dotfiles]