---
# ==============================================================================
# Playbook: Hadev's Workstation Setup
# Description: Standardizes development environment on Ubuntu/Debian.
# ==============================================================================

- name: Standardize Laptop Setup
  hosts: my_laptop

  tasks:

    # --------------------------------------------------------------------------
    # 1. System Updates & Core Packages
    # --------------------------------------------------------------------------
    - name: Update package cache (Ubuntu/Debian)
      become: true
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Common Utilities
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        # Essentials
        - git           # Version control
        - curl          # Data transfer
        - wget          # File download
        - vim           # Text editor
        - tmux          # Terminal multiplexer
        - htop          # Process viewer
        # Modern CLI Enhancements
        - neofetch      # System info display
        - bat           # Syntax highlighting for cat
        - fzf           # Fuzzy file finder

    - name: Install Build Dependencies
      become: true
      apt:
        name:
          - build-essential
          - python3-pip
      when: ansible_os_family == "Debian"

    # --------------------------------------------------------------------------
    # 2. Filesystem & Structure
    # --------------------------------------------------------------------------
    - name: Create Standard Project Directories
      file:
        path: "{{ ansible_user_dir }}/Projects/{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - Code      # Active development
        - Study     # Certifications and books
        - Lab       # VMs and infrastructure
        - Scratch   # Temporary testing

    # --------------------------------------------------------------------------
    # 3. Configuration Management
    # --------------------------------------------------------------------------
    - name: Configure Bash Aliases
      blockinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        block: |
          # Ansible Managed Configuration
          alias cat='batcat'  # Upgrade cat to bat
          neofetch            # Show sys info on login

    - name: Configure Git Global Identity
      git_config:
        scope: global
        name: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "user.name", value: "Hector Alvarez" }
        - { key: "user.email", value: "alvarez.hectorm@outlook.com" }
        - { key: "init.defaultBranch", value: "main" }

    # --------------------------------------------------------------------------
    # 4. Security & Access
    # --------------------------------------------------------------------------
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Generate SSH Key (Ed25519)
      openssh_keypair:
        path: "{{ ansible_user_dir }}/.ssh/id_ed25519"
        type: ed25519
        comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
        state: present
      register: ssh_key_gen

    - name: Display Public Key (Copy this to GitHub)
      debug:
        msg: "{{ ssh_key_gen.public_key }}"
      when: ssh_key_gen.changed