---
- name: Standardize Laptop Setup
  hosts: my_laptop

  tasks:
    - name: Update package cache (Ubuntu/Debian)
      become: true
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Core Packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - htop
        - vim
        - wget
        - tmux

    - name: Create Project Directory Structure
      file:
        path: "{{ ansible_user_dir }}/Projects/{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - Code
        - Study
        - Lab
        - Scratch

    - name: Install Ubuntu-specific tools
      become: true
      apt:
        name:
          - build-essential
          - python3-pip
      when: ansible_os_family == "Debian"

    - name: Configure Git Global Settings
      git_config:
        scope: global
        name: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "user.name", value: "Hector Alvarez" }
        - { key: "user.email", value: "alvarez.hectorm@outlook.com" }
        - { key: "init.defaultBranch", value: "main" }