---
# ==============================================================================
# Core Role: Default Variables
# ==============================================================================

# ------------------------------------------------------------------------------
# Directory Structure
# ------------------------------------------------------------------------------
project_folders:
  - Code
  - Study
  - Lab
  - Scratch

# ------------------------------------------------------------------------------
# Git Configuration
# ------------------------------------------------------------------------------
git_config:
  - { key: "user.name", value: "{{ user_git_name }}" }
  - { key: "user.email", value: "{{ user_git_email }}" }
  - { key: "init.defaultBranch", value: "main" }

# ------------------------------------------------------------------------------
# User Scripts (~/.local/bin)
# ------------------------------------------------------------------------------
# Default to empty list if not defined in config.yml
executable_scripts: "{{ user_custom_scripts | default([], true) }}"
