---
- name: Template bashrc_extras
  template:
    src: bashrc_extras.j2
    dest: "{{ ansible_user_dir }}/.bashrc_extras"
  tags: [dotfiles]

- name: Template tmux configuration
  template:
    src: tmux.conf.j2
    dest: "{{ ansible_user_dir }}/.tmux.conf"
  tags: [dotfiles]

- name: Ensure source ~/.bashrc_extras in .bashrc
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "source ~/.bashrc_extras"
    state: present
  tags: [dotfiles]

- name: Install font and compression utilities
  become: true
  apt:
    name:
      - unzip
      - fontconfig
    state: present

- name: Create local fonts directory
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    state: directory
    mode: '0755'

- name: Download Meslo Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Meslo.zip
    dest: "/tmp/Meslo.zip"

- name: Unzip Nerd Font
  unarchive:
    src: "/tmp/Meslo.zip"
    dest: "{{ ansible_user_dir }}/.local/share/fonts"
    remote_src: yes

- name: Refresh font cache
  command: fc-cache -fv
  changed_when: false

- name: Install Starship prompt
  become: true
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship