---
# ==============================================================================
# Role Defaults: System
# ==============================================================================

# ------------------------------------------------------------------------------
# System Packages
# ------------------------------------------------------------------------------
common_packages:
  # Essentials
  - git
  - curl
  - wget
  - vim
  - tmux
  - htop
  # Modern CLI Tools
  - bat
  - fzf
  - xclip
# Databases
  - sqlite3
# Linters
  - ansible-lint
  - yamllint

python_build_deps:
  # Pyenv Build Dependencies (Required to compile Python)
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev