---
- name: Install Pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_user_dir }}/.pyenv"
    update: yes
  tags: [python]

- name: Install Pyenv Virtualenv Plugin
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ ansible_user_dir }}/.pyenv/plugins/pyenv-virtualenv"
    update: yes
  tags: [python]

- name: Ensure User Ownership of Pyenv
  become: true
  command: "chown -hR {{ ansible_user_id }}:{{ ansible_user_id }} {{ ansible_user_dir }}/.pyenv"
  changed_when: false
  tags: [python]

- name: Install NVM
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ ansible_user_dir }}/.nvm"
    version: v0.40.1
    update: yes
    recursive: no
  tags: [nvm]

- name: Fix NVM Permissions
  become: true
  command: "chown -hR {{ ansible_user_id }}:{{ ansible_user_id }} {{ ansible_user_dir }}/.nvm"
  changed_when: false
  tags: [nvm]
